apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: log-fbit
  labels:
    app.kubernetes.io/name: fluent-bit

data:
  # 적용될 플런트비트 설정
  fluent-bit.conf: |
    [SERVICE]
        Flush             1
        Daemon            off
        Parsers_File      parsers.conf
        #Log_Level         trace

    [INPUT]
        Name              tail
        Tag               kube.*
        Parser            docker
        Path              /var/log/containers/*.log
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10

    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        Keep_log            Off
        Merge_Log           On
        Merge_Log_Key       log_processed
        Annotations         Off
        labels              Off
    
    [OUTPUT]
        Name forward	
        Match *
        Host 10.13.113.231
        Port 24224
    
    #[OUTPUT]
    #    Name stdout
    #    Match *

    
  parsers.conf: |
    [PARSER]
        Name              docker
        Format            json
        Time_Key          time
        Time_Format       %Y-%m-%dT%H:%M:%S.%L
        Time_Keep         On
        # Command       | Decoder   | Field | Optional Action   |
        # ==============|===========|=======|===================|
        Decode_Filed_As   json     log
