---
_meta:
  type: "config"
  config_version: 2

config:
  dynamic:
    http:
      anonymous_auth_enabled: false
      xff:
        enabled: false
        internalProxies: '192\.168\.0\.10|192\.168\.0\.11' # left as-is for now.
        #remoteIpHeader:  'x-forwarded-for'
    authc:
      # 기본 인증
      basic_internal_auth_domain:
        description: "Authenticate via HTTP Basic against internal users database"
        http_enabled: true
        transport_enabled: true
        order: 0
        http_authenticator:
          type: basic
          challenge: false
        authentication_backend:
          type: intern    
      # openid 인증
      openid_auth_domain:
        description: "Authenticate via Keycloak OpenID"
        http_enabled: true
        transport_enabled: true
        order: 1
        http_authenticator:
          type: openid
          challenge: false
          config:
            subject_key: preferred_username
            # openId 연동 roles
            roles_key: roles
            # openId 연동 할 로그인 기본 주소(키클락)
            openid_connect_url: '<Keycloak URL>/auth/realms/<realm>/.well-known/openid-configuration'
            verify_hostnames: false                                  
            #ssl 적용
            enable_ssl: true
            #SSL 인증키 위치
            pemtrustedcas_filepath: '/etc/elasticsearch/root-ca.pem'
        authentication_backend:
          type: noop